[project]
name = "fastapi-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.135.1",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.17",
    "langchain-openai>=0.3.0",
    "langchain-qdrant>=1.1.0",
    "langchain-text-splitters>=1.1.1",
    "pydantic-settings>=2.13.1",
    "pypdf>=6.7.5",
]

[dependency-groups]
dev = [
    "ruff>=0.15.20",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D1", "D202", "D203", "D212"]